extends Resource
class_name MapGrid


const ENVIRONMENTS = {
  "core": {
    "name": "Core's Edge",
    "gradient": preload("res://game/terrain/res/cores_edge_color_gradient.tres"),
    "curve": preload("res://game/terrain/res/cores_edge_elevation_curve.tres"),
    "height": 35,
    "scale": 1.25,
    "navigable_range": [0.308, 0.312],
  },
  "rim": {
    "name": "The Rim Eternal",
    "gradient": preload("res://game/terrain/res/rim_eternal_color_gradient.tres"),
    "curve": preload("res://game/terrain/res/rim_eternal_elevation_curve.tres"),
    "height": 30,
    "scale": 1.75,
    "navigable_range": [0.498, 0.502],
  },
  "void": {
    "name": "The Voidlands",
    "gradient": preload("res://game/terrain/res/voidlands_color_gradient.tres"),
    "curve": preload("res://game/terrain/res/voidlands_elevation_curve.tres"),
    "height": 40,
    "scale": 2.2,
    "navigable_range": [0.498, 0.502],
  },
}


## Map Settings
# Terrain Environment
export(String) var environment = "core"
# Map length/width (maps are always square)
export(int) var map_size = 65
# Random seeds allow random-yet-repeatable maps
export(int) var terrain_seed = 2
# Actual forest locations, initially generated by StateGenerator
export(Array) var forests

# Environment lookup helper
var environment_settings setget , get_environment_settings
func get_environment_settings(): return ENVIRONMENTS[self.environment]
